name: your_hit_point
description: visualize your hitpoint.
publish_to: "none"
version: 0.9.2

assets:
  -.env

environment:
  sdk: ">=3.0.0-431.0.dev <4.0.0"

dependencies:
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.0
  fluttericon: ^2.0.0
  salomon_bottom_bar: ^3.3.2
  vector_math: ^2.1.4
  shared_preferences: ^2.1.1
  http: ^1.0.0
  logger: ^1.3.0
  path_provider: ^2.0.15
  flutter_localizations:
    sdk: flutter 
  provider: ^6.0.5
  url_launcher: ^6.1.14
  uuid: ^4.1.0
  flutter_web_auth_2: ^3.0.2
  pkce: ^1.1.0+1
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.0
  riverpod_generator: ^2.3.5
  intl: ^0.18.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  crypto: ^3.0.3
  flutter_pw_validator: ^1.6.0
  email_validator: ^2.1.17
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/bottle.png
    - assets/images/heartshock.png
    - assets/images/heartshock2.jpg
    - assets/images/illust_normal.jpg
    - assets/images/fitbit_icon.png

flutter_launcher_icons:
  android: true 
  ios: true
  image_path: "lib/assets/yourHP_icon.jpg"
  adaptive_icon_background: "#00a3af"
  adaptive_icon_foreground: "lib/assets/app_icon.jpg"

fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Thin.otf
          weight: 100
