// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSr6SvgGyTG07602KF6-Hf3B96OD9pVrY',
    appId: '1:752312138768:web:ec77a204dfcb827f9c1e95',
    messagingSenderId: '752312138768',
    projectId: 'your-hit-point',
    authDomain: 'your-hit-point.firebaseapp.com',
    storageBucket: 'your-hit-point.appspot.com',
    measurementId: 'G-VDEXD5B8PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuk9myCg9qZ3VavxEmOPevuB4oMXNSSxI',
    appId: '1:752312138768:android:de90258b66345ded9c1e95',
    messagingSenderId: '752312138768',
    projectId: 'your-hit-point',
    storageBucket: 'your-hit-point.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgvF5FfV3cwTedfhizoSsKQcKOpa39m4',
    appId: '1:752312138768:ios:3136e4d9503535149c1e95',
    messagingSenderId: '752312138768',
    projectId: 'your-hit-point',
    storageBucket: 'your-hit-point.appspot.com',
    iosClientId: '752312138768-nqagnfugdv6bd26s312ln4bkfnqb69ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.grenze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKgvF5FfV3cwTedfhizoSsKQcKOpa39m4',
    appId: '1:752312138768:ios:d564fa2f725a9f029c1e95',
    messagingSenderId: '752312138768',
    projectId: 'your-hit-point',
    storageBucket: 'your-hit-point.appspot.com',
    iosClientId: '752312138768-2kplrnr8tansk693v7ui0nv0bgiualdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.grenze.RunnerTests',
  );
}
