name: grenze
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-431.0.dev <4.0.0'

dependencies:
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.0.3
  flutter_chat_types: ^3.6.0
  device_info_plus: ^9.0.2
  firebase_analytics: ^10.4.2
  shared_preferences: ^2.1.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
