name: grenze
description: A new Flutter project.
publish_to: "none"
version: 0.1.3

environment:
  sdk: ">=3.0.0-431.0.dev <4.0.0"

dependencies:
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.0
  fluttericon: ^2.0.0
  salomon_bottom_bar: ^3.3.2
  vector_math: ^2.1.4
  shared_preferences: ^2.1.1
  http: ^1.0.0
  logger: ^1.3.0
  path_provider: ^2.0.15
  flutter_native_splash: ^2.3.1
  flutter_localizations:
    sdk: flutter 
  provider: ^6.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/bottle.png
    - assets/images/heartshock.png
    - assets/images/heartshock2.jpg
    - assets/images/illust_normal.jpg

# flutter_icons:
#   android: true 
#   ios: true
#   image_path: "assets/icon/yourHP_icon_circlecut.png"
#   adaptive_icon_background: "#00A5BF"
#   adaptive_icon_foreground: "assets/icon/yourHP_icon_circlecut.png"

# flutter_native_splash:
#   image: "assets/icon/yourHP_icon_circlecut.png" 
#   color: "#00A5BF"
  